# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

  trigger:
  - master

  pool:
     vmImage: 'Ubuntu-16.04'

# Bash
# Run a Bash script on macOS, Linux, or Windows

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: echo $MYSECRET
    env:
      MySecret: $(Foo)

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
       curl -X POST \ "https://testing.sweagle.com/api/v1/tenant/metadata-parser/parse" -H "Authorization: bearer c1275a8c-ed45-4dbe-a7d4-e030dbe429db" -d "mds=jenkinsConf&parser=all&args=&mdsArgs=&format=CSV&tag=Version:1.7.18&mdsTags="

  - task: PublishCodeCoverageResults@1
    inputs:
     codeCoverageTool: "JaCoCo"
     summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
     reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
     failIfCoverageEmpty: true