# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

  trigger:
  - master

  pool:
     vmImage: 'Ubuntu-16.04'

# Bash
# Run a Bash script on macOS, Linux, or Windows

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: echo $MYSECRET
    env:
      MySecret: $(Foo)

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        curl -s -X POST -H "Authorization: bearer 783d4f5b-c260-4cce-936e-00d2483875ab" 'https://testing.sweagle.com/api/v1/data/bulk-operations/dataLoader/upload?nodePath=Eldorado,releases,pipeline,goCD&format=json&tag=V1.2&allowDelete=false&autoApprove=true&storeSnapshotResults=true&validationLevel=error' -H 'Content-Type: application/json' -d '{"nodeFlavor":"chocolate"}'

  - task: PublishCodeCoverageResults@1
    inputs:
     codeCoverageTool: "JaCoCo"
     summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
     reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
     failIfCoverageEmpty: true