# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

  trigger:
  - master

  pool:
    vmImage: 'Ubuntu-16.04'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.

      cd /Users/boondock/Documents/Technical
    curl -X POST \
    https://testing.sweagle.com/api/v1/tenant/metadata-parser/parse -H "Authorization: bearer 783d4f5b-c260-4cce-936e-00d2483875ab" -d "mds=release1.0&parser=all&args=&mdsArgs=&format=JSON&tag=V.2.1.3&mdsTags="